routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ForumController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ThreadController;
use App\Http\Controllers\UsersController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//----------------------------Index-------------------------------------------
Route::get('/', [HomeController::class, 'home']);

//----------------------------Forum-------------------------------------------
// Route::get('/thread', [ForumController::class, 'thread']);
// Route::get('/submit', [ForumController::class, 'submit']);
// Route::get('/comment', [ForumController::class, 'comment']);

//----------------------------Authentication----------------------------------
Route::get('/register', [AuthController::class, 'register']);
Route::post('/register', [AuthController::class, 'store']);
Route::get('/login', [AuthController::class, 'login']);
//Route::get('/success', 'App\Http\Controllers\Auth\AuthController@success');

//----------------------------Profile----------------------------------------
Route::get('/users_profile', [UsersController::class, 'users_profile']);

//----------------------------CRUD Thread----------------------------------------
Route::resource('thread', ThreadController::class);

//----------------------------CRUD Profile----------------------------------------
Route::resource('users', UsersController::class);

resources/views/pages/edit.blade.php
@extends('layout.main')

@section('isi')

<div class="container">      
  <form action="/thread/{{$thread->id}}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('put')
    <div class="card mt-5">
      <div class="card-body">
        <div class="form-group">
          <label>Title</label>
          <input type="text" value="{{$thread->topic}}" name="topic" class="form-control" id="exampleFormControlInput1">
        </div>
        @error('topic')
          <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="form-group">
          <label>Tags</label>
          <select name="tags_id" class="form-control">
            <option value="">-- Pilih Tag --</option>
            @foreach ($tags as $item)

                @if ($item->id === $thread->tags_id)
                <option value="{{$item->id}}" selected>{{$item->tag}}</option>
                @else
                <option value="{{$item->id}}">{{$item->tag}}</option>
                @endif
                
            @endforeach
          </select>
        </div>
        @error('tag')
          <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="form-group">
          <label>Images</label>
          <input type="file" name="img" class="form-control-file" id="exampleFormControlFile1">
        </div>
        @error('img')
          <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="form-group">
          <label>Isi</label>
          <textarea class="form-control" {{$thread->description}} name="description" id="exampleFormControlTextarea1" rows="3"></textarea>
        </div>
        @error('description')
          <div class="alert alert-danger">{{ $message }}</div>
        @enderror
      </div>
      <div class="card-footer bg-white border-0">
        <button class="btn btn-dark float-right" type="submit">Post</button>
      </div>
    </div>
  </form>
</div>

@endsection

resources/views/pages/index.blade.php
@extends('layout.main')

@section('isi')

<div class="container-fluid mb-3 pt-3 h-100 bg-light mx-0 h-100" >      
    <div class="row ">
      <nav class="col-md-2 d-none d-md-block navbar-light sidebar">
        <div class="sidebar-sticky">
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link active" href="#">
                <span data-feather="home"></span>
                Dashboard <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="file"></span>
                Orders
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="shopping-cart"></span>
                Products
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="users"></span>
                Customers
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="bar-chart-2"></span>
                Reports
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="layers"></span>
                Integrations
              </a>
            </li>
          </ul>
      
          <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Saved reports</span>
            <a class="d-flex align-items-center text-muted" href="#">
              <span data-feather="plus-circle"></span>
            </a>
          </h6>
          <ul class="nav flex-column mb-2">
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="file-text"></span>
                Current month
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="file-text"></span>
                Last quarter
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="file-text"></span>
                Social engagement
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="file-text"></span>
                Year-end sale
              </a>
            </li>
          </ul>
        </div>
      </nav>
      <div class="col-md-10 ml-sm-auto col-lg-10">
        <div class="row d-none d-md-block justify-content-center">
          {{-- contentnav --}}
          <nav class="navbar nav-fill w-100 navbar-light justify-content-center pt-2 navbar-expand-lg d-flex">
            <ul class="navbar-nav mr-auto justify-content-center">
              <li class="nav-item"><a class="nav-link" href="#">Website Name</a></li>
              <li class="nav-item"><a class="nav-link" href="#">Website Name</a></li>
              <li class="nav-item"><a class="nav-link" href="#">Website Name</a></li>
              <li class="nav-item"><a class="nav-link" href="#">Website Name</a></li>
            </ul>
            <a href="/thread/create" class="btn btn-dark my-2 my-sm-0 ml-auto">New Thread</a>
          </nav>
          {{-- contentnav end --}}
        </div>
      <div class="row">
        <div class="col-md-8 ml-sm-auto col-lg-8">
          @forelse ($thread as $item)
          <div class="card m-0 rounded-0 border-0 shadow-sm">
              <div class="border-bottom">
                  <div class="card-header bg-white border-0">
                      <div class="media flex-wrap w-100 align-items-center"> <img src="{{asset('img/1.png')}}" class="d-block ui-w-40 rounded-circle" height="44px">
                          <div class="media-body ml-3"> <a href="" >Tom Harry</a>
                              <div class="text-muted small">13 days ago</div>
                          </div>
                          <div class="text-muted small ml-3">
                              <div>Member since <strong>01/1/2019</strong></div>
                              <div><strong>134</strong> posts</div>
                          </div>
                      </div>
                  </div>
                  <div class="card-body p-3 border-0">
                      <img class="card-img mb-2" src="{{asset('img/'.$item->img)}}" alt="card-image-cap">
                      <h4>{{$item->topic}}</h4>
                      <p class="card-text">{{Str::limit($item->description, 100)}}</p>
                  </div>
                  <form action="{{route('thread.destroy',$item->id)}}" method="post">
                    @csrf
                    @method('delete')
                  <div class="card-footer d-flex bg-white border-0 justify-content-start align-items-center px-0 pt-0 pb-3">
                    <div class="px-3"> 
                        <a href="{{route('thread.show',$item->id)}}" class="d-inline-flex align-items-center align-middle"> 
                            Comment 
                        </a>
                    </div>
                    <div class="px-3"> 
                      <a href="{{route('thread.edit',$item->id)}}" class="d-inline-flex align-items-center align-middle"> 
                          Edit
                      </a>
                    </div>
                    
                      <input type="submit" class="btn btn-dark ml-auto mr-3" value="delete">
                    
                  </div>
                </form>
              </div>
          </div>
          @empty
              
          @endforelse              
        </div>
        <div class="col-md-4 d-none d-md-block w-100">
            <div class="jumbotron jumbotron-fluid">
                <div class="container">
                  <h1 class="display-4">Ads Here</h1>
                  <p class="lead">This where the magic do, please click the linke <a class="text-dark" href="https://youtu.be/dQw4w9WgXcQ"><b>HERE</b></a></p>
                </div>
            </div>
        </div>
        </div>  
      </div>
    </div>   
</div>

@endsection

resources/views/pages/login.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{asset('bootstrap/css/bootstrap.css')}}">
    <link rel="stylesheet" href="{{asset('css/style.css')}}">
    @stack('style')

    <title>Sanber Forum</title>
  </head>
  <body class="bg-light">
    {{-- navbar --}}
    <nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm">

      <img id="logo" class="d-flex navbar-nav mr-auto" src="{{asset('img/logo.png')}}" width="200px" />
  
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
  
          <form class="form-inline my-4 my-lg-0 mx-lg-5 w-50">
              <input class="form-control mr-sm-2 w-50" type="search" placeholder="Cari" aria-label="Cari">
              <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>
          </form>
          
          <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
              <a class="nav-link" href="/">Return to home<span class="sr-only">(current)</span></a>
              </li>
          </ul>
  
      </div>
  </nav>
    {{-- content --}}
    @yield('')
    <div class="container pb-5" >
      <div class="row justify-content-center">
        <div class="col-md-4">
          <main class="card shadow-sm form-signin mt-5">
            <form>
              <img class="mb-4" src="{{asset('img/logo.png')}}" width="200px">
              <h1 class="h3 mb-3 fw-normal">Sign in to your account</h1>
          
              <div class="form-floating">
                <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
                <label for="floatingInput">Email address</label>
              </div>
              <div class="form-floating">
                <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
                <label for="floatingPassword">Password</label>
              </div>
          
              <div class="checkbox mb-3">
                <label>
                  <input type="checkbox" value="remember-me"> Remember me
                </label>
              </div>
              <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
              
            </form>
            <small class="d-block text-center mt-3">Not having an account ? <a href="/register">Register here</a>
            </small>
          </main>
        </div>
      </div>
    </div>
    
    {{-- content end --}}
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

resources/views/pages/register.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{asset('bootstrap/css/bootstrap.css')}}">
    <link rel="stylesheet" href="{{asset('css/style.css')}}">
    @stack('style')

    <title>Sanber Forum</title>
  </head>
  <body class="bg-light">
    {{-- navbar --}}
    <nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm">

      <img id="logo" class="d-flex navbar-nav mr-auto" src="{{asset('img/logo.png')}}" width="200px" />
  
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
  
          <form class="form-inline my-4 my-lg-0 mx-lg-5 w-50">
              <input class="form-control mr-sm-2 w-50" type="search" placeholder="Cari" aria-label="Cari">
              <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>
          </form>
          
          <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
              <a class="nav-link" href="/">Return to home<span class="sr-only">(current)</span></a>
              </li>
          </ul>
  
      </div>
  </nav>
    {{-- navbar end --}}
    
    {{-- content --}}
    @yield('')
    <div class="container pb-5">
      <div class="row justify-content-center">
      
        <div class="col-md-4">
          
        <main class="card form-registration mt-5">
          <form method="POST" action="{{url('/users')}}">
            @csrf
            
            <img class="mb-4" src="{{asset('img/logo.png')}}" width="200px">
            <h1 class="h3 mb-3 fw-normal">Register here</h1>
        
            <div class="form-floating pb-2">
              <input type="name" class="form-control" id="name" placeholder="Name">
            </div>
      
            <div class="form-floating pb-2">
              <input type="username" class="form-control" id="username" placeholder="Username">
            </div>
            
            <div class="form-floating pb-2">
              <input type="email" class="form-control" id="email" placeholder="Email">
            </div>
      
            <div class="form-floating pb-2">
              <input type="password" class="form-control" id="password" placeholder="Password">
            </div>
      
            <button class="w-100 btn btn-lg btn-primary mt-3" type="submit">Register</button>
            
          </form>
          <small class="d-block text-center mt-3">Already registered ? <a href="/login">Login</a></small>
        </main>
      
        </div>
      </div>
    </div>
    {{-- content end --}}
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

resources/views/pages/subcomment.blade.php
@extends('layout.main')

@section('isi')

  <div class="container pb-5" >      
    <div class="card m-0 mt-5 rounded-0 border-0 shadow-sm">
        <div class="border-bottom">
            <div class="card-header bg-white border-0">
                <div class="media flex-wrap w-100 align-items-center"> <img src="{{asset('img/1.png')}}" class="d-block ui-w-40 rounded-circle" height="44px">
                    <div class="media-body ml-3"> <a href="" >Tom Harry</a>
                        <div class="text-muted small">13 days ago</div>
                    </div>
                    <div class="text-muted small ml-3">
                        <div>Member since <strong>01/1/2019</strong></div>
                        <div><strong>134</strong> posts</div>
                    </div>
                </div>
            </div>
            <div class="card-body p-3 border-0">
                <p> For me, getting my business website made was a lot of tech wizardry things. Thankfully i get an ad on Facebook ragarding commence website. I get connected with BBB team. They made my stunning website live in just 3 days. With the increase demand of online customers. I had to take my business online. BBB Team guided me at each step and enabled me to centralise my work and have control on all aspect of my online business. </p>
            </div>
            <div class="card-footer d-flex flex-wrap bg-white border-0 justify-content-start align-items-center px-0 pt-0 pb-3">
                <div class="px-3"> 
                    <a href="" class="text-muted d-inline-flex align-items-center align-middle"> 
                        Comments 
                    </a> 
                </div>
            </div>
        </div>
    </div>
    
    <form>
        <div class="card mt-5">
          <div class="card-body">
            <div class="form-group">
              <label for="exampleFormControlTextarea1">Example textarea</label>
              <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>
          </div>
          <div class="card-footer bg-white border-0">
            <button class="btn btn-dark float-right" type="submit">Post</button>
          </div>
        </div>
    </form>

    <div class="card m-0 mt-2 rounded-0 border-0 shadow-sm">
        <div class="border-bottom">
            <div class="card-header bg-white border-0">
                <div class="media flex-wrap w-100 align-items-center"> <img src="{{asset('img/1.png')}}" class="d-block ui-w-40 rounded-circle" height="44px">
                    <div class="media-body ml-3"> <a href="" >Tom Harry</a>
                        <div class="text-muted small">13 days ago</div>
                    </div>
                    <div class="text-muted small ml-3">
                        <div>Member since <strong>01/1/2019</strong></div>
                        <div><strong>134</strong> posts</div>
                    </div>
                </div>
            </div>
            <div class="card-body p-3 border-0">
                <p> For me, getting my business website made was a lot of tech wizardry things. Thankfully i get an ad on Facebook ragarding commence website. I get connected with BBB team. They made my stunning website live in just 3 days. With the increase demand of online customers. I had to take my business online. BBB Team guided me at each step and enabled me to centralise my work and have control on all aspect of my online business. </p>
            </div>
            <div class="card-footer d-flex flex-wrap bg-white border-0 justify-content-start align-items-center px-0 pt-0 pb-3">
                <div class="px-3"> 
                    <a href="" class="text-muted d-inline-flex align-items-center align-middle"> 
                        Comments 
                    </a> 
                </div>
            </div>
        </div>
    </div>

    <div class="card m-0 mt-2 rounded-0 border-0 shadow-sm">
        <div class="border-bottom">
            <div class="card-header bg-white border-0">
                <div class="media flex-wrap w-100 align-items-center"> <img src="{{asset('img/1.png')}}" class="d-block ui-w-40 rounded-circle" height="44px">
                    <div class="media-body ml-3"> <a href="" >Tom Harry</a>
                        <div class="text-muted small">13 days ago</div>
                    </div>
                    <div class="text-muted small ml-3">
                        <div>Member since <strong>01/1/2019</strong></div>
                        <div><strong>134</strong> posts</div>
                    </div>
                </div>
            </div>
            <div class="card-body p-3 border-0">
                <p> For me, getting my business website made was a lot of tech wizardry things. Thankfully i get an ad on Facebook ragarding commence website. I get connected with BBB team. They made my stunning website live in just 3 days. With the increase demand of online customers. I had to take my business online. BBB Team guided me at each step and enabled me to centralise my work and have control on all aspect of my online business. </p>
            </div>
            <div class="card-footer d-flex flex-wrap bg-white border-0 justify-content-start align-items-center px-0 pt-0 pb-3">
                <div class="px-3"> 
                    <a href="" class="text-muted d-inline-flex align-items-center align-middle"> 
                        Comments 
                    </a>
                </div>
                <button class="btn btn-dark float-right" type="submit">Post</button>
            </div>
        </div>
    </div>

  </div>

@endsection

resources/views/pages/submit.blade.php
@extends('layout.main')

@section('isi')

<div class="container">      
  <form action="/thread" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="card mt-5">
      <div class="card-body">
        <div class="form-group">
          <label>Title</label>
          <input type="text" name="topic" class="form-control" id="exampleFormControlInput1">
        </div>
        @error('topic')
          <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="form-group">
          <label>Tags</label>
          <select name="tags_id" class="form-control">
            <option value="">-- Pilih Tag --</option>
            @foreach ($tags as $item)
                <option value="{{$item->id}}">{{$item->tag}}</option>
            @endforeach
          </select>
        </div>
        @error('tag')
          <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="form-group">
          <label>Images</label>
          <input type="file" name="img" class="form-control-file" id="exampleFormControlFile1">
        </div>
        @error('img')
          <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="form-group">
          <label>Isi</label>
          <textarea class="form-control" name="description" id="exampleFormControlTextarea1" rows="3"></textarea>
        </div>
        @error('description')
          <div class="alert alert-danger">{{ $message }}</div>
        @enderror
      </div>
      <div class="card-footer bg-white border-0">
        <button class="btn btn-dark float-right" type="submit">Post</button>
      </div>
    </div>
  </form>
</div>

@endsection

resources/views/pages/thread.blade.php
@extends('layout.main')

@section('isi')

  <div class="container mt-5 pb-5" >     
    
    <div class="card m-0 rounded-0 border-0 shadow-sm">
        <div class="border-bottom">
            <div class="card-header bg-white border-0">
                <div class="media flex-wrap w-100 align-items-center"> <img src="{{asset('img/1.png')}}" class="d-block ui-w-40 rounded-circle" height="44px">
                    <div class="media-body ml-3"> <a href="" >Tom Harry</a>
                        <div class="text-muted small">13 days ago</div>
                    </div>
                    <div class="text-muted small ml-3">
                        <div>Member since <strong>01/1/2019</strong></div>
                        <div><strong>134</strong> posts</div>
                    </div>
                </div>
            </div>
            <div class="card-body p-3 border-0">
                <img class="card-img mb-2" src="{{asset('img/'.$thread->img)}}" alt="card-image-cap">
                <p class="card-text">{{Str::limit($thread->description, 15)}}</p>
            </div>
            <div class="card-footer d-flex flex-wrap bg-white border-0 justify-content-start align-items-center px-0 pt-0 pb-3">
            </div>
        </div>
    </div> 
    
    
    <form>
        <div class="card mt-5">
          <div class="card-body">
            <div class="form-group">
              <label for="exampleFormControlTextarea1">Example textarea</label>
              <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>
          </div>
          <div class="card-footer bg-white border-0">
            <button class="btn btn-dark float-right" type="submit">Post</button>
          </div>
        </div>
    </form>

    <div class="card m-0 mt-2 rounded-0 border-0 shadow-sm">
        <div class="border-bottom">
            <div class="card-header bg-white border-0">
                <div class="media flex-wrap w-100 align-items-center"> <img src="{{asset('img/1.png')}}" class="d-block ui-w-40 rounded-circle" height="44px">
                    <div class="media-body ml-3"> <a href="" >Tom Harry</a>
                        <div class="text-muted small">13 days ago</div>
                    </div>
                    <div class="text-muted small ml-3">
                        <div>Member since <strong>01/1/2019</strong></div>
                        <div><strong>134</strong> posts</div>
                    </div>
                </div>
            </div>
            <div class="card-body p-3 border-0">
                <p> For me, getting my business website made was a lot of tech wizardry things. Thankfully i get an ad on Facebook ragarding commence website. I get connected with BBB team. They made my stunning website live in just 3 days. With the increase demand of online customers. I had to take my business online. BBB Team guided me at each step and enabled me to centralise my work and have control on all aspect of my online business. </p>
            </div>
            <div class="card-footer d-flex bg-white border-0 justify-content-start align-items-center px-0 pt-0 pb-3">
                <div class="px-3"> 
                    <a href="" class="text-muted d-inline-flex align-items-center align-middle"> 
                        Comments 
                    </a>
                </div>
                <button class="btn btn-dark ml-auto mr-3" type="submit">Post</button>
            </div>
        </div>
    </div>

  </div>

@endsection